// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

uint dimension;
float radius;

RWStructuredBuffer<float> voxel;

[numthreads(8,8,8)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	float3 centre = float3(dimension/2, dimension/2, dimension/2);
	if(distance(float3(id.x, id.y, id.z), centre) < radius){
		voxel[id.x + id.y*dimension+ id.z*dimension*dimension] = 1.0;
	}else{
		voxel[id.x + id.y*dimension+ id.z*dimension*dimension] = -1.0;
	}
}
